PROJECTID = 'indranil-24011994-04'
CON_REGION = 'us-central1'
CON_BIGQUERY_DATASET = 'poc_composer_dataflow'
CON_BIGQUERY_TABLE_Dataflow = 'df_stock_details'
CON_BIGQUERY_TABLE_Composer = 'comp_stock_details'
CON_AWS_BUCKET = 's3-bucket-test-0001'
